name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Configure
      shell: bash
      run: |
        sudo apt-get install -y curl libssl-dev libcurl4-openssl-dev
        mkdir build
        cmake -S . -B build

    - name: Make
      shell: bash
      run: |
        cmake --build build
